CREATE DATABASE "StoreNet";

\c "StoreNet";

CREATE TABLE "Customers"(
	"Id" bigint GENERATED BY DEFAULT AS IDENTITY,
	"Name" varchar(100) NOT NULL,
	"Lastname" varchar(100) NOT NULL,
	"Address" varchar(100) NOT NULL,
	PRIMARY KEY("Id")
);

CREATE TABLE "Products"(
	"Id" bigint GENERATED ALWAYS AS IDENTITY,
	"Barcode" varchar(100) NOT NULL,
	"Description" varchar(100) NULL,
	"Image" BYTEA NULL,
	"Price" decimal(19, 4) NOT NULL,
	"Stock" int NOT NULL,
	PRIMARY KEY ("Id")
);

CREATE TABLE "ProductStore"(
	"Id" bigint GENERATED ALWAYS AS IDENTITY,
	"ProductId" int NOT NULL,
	"StoreId" int NOT NULL,
	"CreatedDate" TIMESTAMP(3) NULL,
	"UpdatedDate" TIMESTAMP(3) NULL,
 	PRIMARY KEY ("Id")
);

CREATE TABLE "Sales"(
	"Id" bigint GENERATED ALWAYS AS IDENTITY,
	"CustomerId" int NOT NULL,
	"ProductId" int NOT NULL,
	"Quantity" int NOT NULL,
	"UnitPrice" decimal(19, 4) NOT NULL,
	"Total" decimal(19, 4) NOT NULL,
	"CreatedDate" TIMESTAMP(3) NULL,
	"UpdatedDate" TIMESTAMP(3) NULL,
 	PRIMARY KEY ("Id")
);

CREATE TABLE "Stores"(
	"Id" bigint GENERATED ALWAYS AS IDENTITY,
	"Branch" varchar(100) NOT NULL,
	"Address" varchar(100) NOT NULL,
	PRIMARY KEY ("Id")
);

INSERT INTO "Customers" ("Name", "Lastname", "Address") VALUES (N'Gilbert', N'Tamayo', N'Aqui cerca de una escuela');
INSERT INTO "Customers" ("Name", "Lastname", "Address") VALUES (N'Juan', N'Perez', N'Cerca de un super mercado');

INSERT INTO "Products" ("Barcode", "Description", "Image", "Price", "Stock") VALUES (N'123456789', N'Coca-Cola', NULL, CAST(30.0000 AS Decimal(19, 4)), 599);
INSERT INTO "Products" ("Barcode", "Description", "Image", "Price", "Stock") VALUES (N'494949848', N'Chetos', NULL, CAST(15.0000 AS Decimal(19, 4)), 800);
INSERT INTO "Products" ("Barcode", "Description", "Image", "Price", "Stock") VALUES (N'1165645498', N'Helado', NULL, CAST(20.0000 AS Decimal(19, 4)), 50);
INSERT INTO "Products" ("Barcode", "Description", "Image", "Price", "Stock") VALUES (N'159498494', N'Kilo de Manzana', NULL, CAST(60.0000 AS Decimal(19, 4)), 798);

INSERT INTO "Sales" ("CustomerId", "ProductId", "Quantity", "UnitPrice", "Total", "CreatedDate", "UpdatedDate") VALUES (1, 1, 100, CAST(10.1000 AS Decimal(19, 4)), CAST(1010.0000 AS Decimal(19, 4)), CAST(N'2023-07-06T18:47:51.600' AS TIMESTAMP(3)), NULL);
INSERT INTO "Sales" ("CustomerId", "ProductId", "Quantity", "UnitPrice", "Total", "CreatedDate", "UpdatedDate") VALUES (1, 1, 100, CAST(30.0000 AS Decimal(19, 4)), CAST(3000.0000 AS Decimal(19, 4)), CAST(N'2023-07-08T18:34:11.430' AS TIMESTAMP(3)), NULL);
INSERT INTO "Sales" ("CustomerId", "ProductId", "Quantity", "UnitPrice", "Total", "CreatedDate", "UpdatedDate") VALUES (1, 4, 2, CAST(60.0000 AS Decimal(19, 4)), CAST(120.0000 AS Decimal(19, 4)), CAST(N'2023-07-10T14:34:43.127' AS TIMESTAMP(3)), NULL);

INSERT INTO "Stores" ("Branch", "Address") VALUES (N'Tienda de la esquina', N'Local de la esquina');
INSERT INTO "Stores" ("Branch", "Address") VALUES (N'Tienda de cozumel', N'Malecón');
INSERT INTO "Stores" ("Branch", "Address") VALUES (N'Tienda matriz', N'Paseo montejo');
INSERT INTO "Stores" ("Branch", "Address") VALUES (N'El amigo Juan', N'Con el Juan');
INSERT INTO "Stores" ("Branch", "Address") VALUES (N'El amigo Luis', N'Con el Luis');
INSERT INTO "Stores" ("Branch", "Address") VALUES (N'Tienda de la esquina', N'En la esquina');

INSERT INTO "ProductStore" ("ProductId", "StoreId", "CreatedDate", "UpdatedDate") VALUES (3, 1, CAST(N'2023-07-07T00:00:00.000' AS TIMESTAMP(3)), CAST(N'2023-07-10T14:11:55.617' AS TIMESTAMP(3)));
INSERT INTO "ProductStore" ("ProductId", "StoreId", "CreatedDate", "UpdatedDate") VALUES (2, 5, CAST(N'2023-07-10T19:22:05.063' AS TIMESTAMP(3)), CAST(N'2023-07-10T19:27:52.153' AS TIMESTAMP(3)));

ALTER TABLE "Products" ALTER COLUMN "Price" SET DEFAULT ((0.00));
ALTER TABLE "Products" ALTER COLUMN "Stock" SET DEFAULT ((0));

ALTER TABLE "ProductStore" ADD CONSTRAINT "FK_ProductStore_Products_ProductId" FOREIGN KEY("ProductId")
REFERENCES "Products" ("Id");

ALTER TABLE "ProductStore" ADD CONSTRAINT "FK_ProductStore_Stores_StoreId" FOREIGN KEY("StoreId")
REFERENCES "Stores" ("Id");

ALTER TABLE "Sales" ADD CONSTRAINT "FK_Sales_Customers_CustomerId" FOREIGN KEY("CustomerId")
REFERENCES "Customers" ("Id");

ALTER TABLE "Sales" ADD CONSTRAINT "FK_Sales_Products_ProductId" FOREIGN KEY("ProductId")
REFERENCES "Products" ("Id");