version: '2'
services:
  web:
    build: .
    command: bash -c "chmod a+x ./run.sh && ./run.sh"
    volumes:
      - .:/usr/src/app
      - /usr/src/app
    ports:
      - "1433:1433"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: P@ssword
      POSTGRES_DB: StoreNet
